# Generated by Django 2.0.7 on 2018-08-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=300)),
                ('hdes', models.CharField(max_length=300)),
                ('hrating', models.CharField(max_length=300)),
                ('hname', models.CharField(max_length=300)),
                ('hphone', models.CharField(max_length=300)),
                ('hemail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=300)),
                ('pname', models.CharField(max_length=300)),
                ('pdes', models.CharField(max_length=300)),
                ('pimage1', models.CharField(max_length=300)),
                ('pimage2', models.CharField(max_length=300)),
                ('pimage3', models.CharField(max_length=300)),
				
				
            ],
        ),
    ]
