# Generated by Django 2.0.7 on 2018-08-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelguide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.AlterField(
            model_name='place',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
