# Generated by Django 2.0.7 on 2018-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelguide', '0002_auto_20180824_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='prating',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
