# Generated by Django 2.0.7 on 2018-08-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelguide', '0004_auto_20180829_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
